from typing import List

class Monitor:
    def __init__(self) -> None:
        self.width: int = ...
        self.height: int = ...
        self.name: str = ...

def get_monitors() -> List[Monitor]:
    ...