version: 2.1

orbs:
  python: circleci/python@1.2
  win: circleci/windows@2.2.0

workflows:
  dedomouse_workflow:
    jobs:
      - build-and-test
      - build-executable-linux:
          filters:
            branches:
              only: main
      - build-executable-windows:
          filters:
            branches:
              only: main

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run mypy
          command: |
            mypy
      - run:
          name: Run pylint
          command: |
            pylint --rcfile=.pylintrc src
      # - run:
      #    name: Run tests
      #    command: pytest 

  build-executable-linux:
    docker:
      - image: achimmihca/circleci-python-dev:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Build executable via pyinstaller
          command: |
            pyinstaller main.spec
      - run:
          name: Zip build artifact
          command: |
            mv dist/main ./DedoMouse
            zip -r DedoMouse.zip DedoMouse
      - store_artifacts:
          path: DedoMouse.zip

  build-executable-windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Remove old python version from PATH
          command: |
            $env:PATH = $env:PATH -Replace "python", "python_to_be_ignored"
            $env:PATH = $env:PATH -Replace "miniconda3", "miniconda3_to_be_ignored"
            echo $env:PATH
      - run:
          name: Install scoop
          command: |
            Set-ExecutionPolicy RemoteSigned -scope CurrentUser
            Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
      - run:
          name: Install latest python via scoop
          command: |
            scoop bucket add extras
            scoop install python
            dir ~/scoop/apps
      - run:
          name: Install Requirements
          command: |
            ~\scoop\apps\python\current\Scripts\pip install -r requirements.txt
      - run:
          name: Build executable via pyinstaller
          command: pyinstaller main.spec
      - run:
          name: Zip build artifact
          command: |
            Compress-Archive -Path .\dist\main\* -DestinationPath .\DedoMouse.zip
      - store_artifacts:
          path: DedoMouse.zip