version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  dedomouse_workflow:
    jobs:
      - build-and-test
      - build-executable:
          filters:
            branches:
              only: main

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run mypy
          command: |
            mypy
      - run:
          name: Run pylint
          command: |
            pylint --rcfile=.pylintrc src
      # - run:
      #    name: Run tests
      #    command: pytest

  build-executable:
    docker:
      - image: achimmihca/circleci-python-dev:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Build executable via pyinstaller
          command: |
            pyinstaller main.spec
      - run:
          name: Zip build artifact
          command: |
            mv dist/main ./DedoMouse
            zip -r DedoMouse.zip DedoMouse
      - store_artifacts:
          path: DedoMouse.zip
