version: 2.1

orbs:
  python: circleci/python@1.2
  win: circleci/windows@2.2.0

workflows:
  dedomouse_workflow:
    jobs:
      - noop

jobs:
  noop:
    docker:
      - image: cimg/python:3.8
    steps: 
      - checkout
